config-version: 1

save:
  sql:
    url: jdbc:mysql://120.220.76.204:3306/minecraft?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    user: minecraft
    password: minecraft
    table: qcpet

player:
  max-display-count: 3

pet:
  rename:
    max-length: 32
    allow-color-codes: true
    invalid-pattern: "[\\r\\n\\t]"
  bath:
    interval-hours: 24
  feed:
    min-times-per-day: 3
    max-times-per-day: 5
